In [11]:
x = 2
3x

6

In [12]:
f(x) = x^2 + 2x - 2

f (generic function with 1 method)

In [16]:
println(f(0))
println(f(1))

-2
1


In [8]:
x = [2, 3]

2-element Array{Int64,1}:
 2
 3

In [2]:
# Make an array of zeros
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [1]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [3]:
zeros(3, 3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [5]:
ones(2, 3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [16]:
@assert 2 == 2
@assert 2 + 2 == 5

AssertionError: AssertionError: 2 + 2 == 5